### ISSUE TITLE
Line/Text is defined multiple times

### ISSUE THREAD

**Issue by Horryportier** [tui-rs-revival/ratatui#208]
## Description

I was trying to migrate my project from tui to this fork and i had everything working but for some reason my project started complaining that crates are not resolved so i've added them but that make ratatui to trow errors about multiple implementation of `Line/Text`. To reiterate it was working just few hours before and i don't think i did anything werid.  

## To Reproduce

Honestly have no idea haw to reproduce this issue.

## Expected behavior

No conflicts in definiton of `List/Text`

## Screenshots

![image](https://github.com/tui-rs-revival/ratatui/assets/42907709/144143b1-e3a5-40a2-a78d-c7ead0f814d1)
![Screenshot from 2023-05-31 22-26-30](https://github.com/tui-rs-revival/ratatui/assets/42907709/edf95fc5-c8fe-495c-87ee-ee13732a3fd6)

## Environment

- OS: Linux 
- Terminal Emulator: kitty 
- Font: 
- Crate version: 0.21.0
- Backend: crossterm

**Comment by Eyesonjune18** [comment]
Can you show me the way that you imported the crate in `Cargo.toml`?

**Comment by Horryportier** [comment]
here you go even tried to delete Corgo.lock to test if it help but its the same
```toml
[package]
name = "Watcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
ratatui = "0.21.0"
riven = "2.19.0"
tokio = { version = "1.27.0", features =   ["full", "macros"] }
```
